### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by 95ImadEL** [cortictechnology/cep#16]
Hello,
First of all I would like to thank you for this excellent work. In fact, I am trying to connect to http://raspberrypi.local/programming. I enter the username pi and the password and it shows me The username does not exist! Thanks in advance.

**Comment by michaelhwn** [comment]
Hi @95ImadEL, did you observe if there were any errors during the setup process? if not, can you please confirm if you can log in to your Raspberry Pi OS using the pi account?

**Comment by 95ImadEL** [comment]
Thank you for your answer, unfortunately I could not find any error during the setup. Also I can connect with the pi login.

**Comment by 95ImadEL** [comment]
This is the used OS 

PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by michaelhwn** [comment]
Thanks for the info @95ImadEL, currently CEP has not updated to fully support the latest Raspberry Pi OS (bullseye), there is an issue in CEP that prevents the user from logging in properly on this latest OS. I will push an update soon to solve this issue. Meanwhile, can you try to use CEP on Raspberry Pi OS Buster instead?

**Comment by 95ImadEL** [comment]
ok I'll do it thanks a lot. I will keep you informed.

**Comment by michaelhwn** [comment]
You are welcome @95ImadEL. I will let you know once the Bullseye support is ready.

**Comment by gris74** [comment]
I have same issue... but on buster

I can access, dev directly from http://ip-address/programming but not via login screen, the login as no effect/redirect

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by michaelhwn** [comment]
Hi @gris74, can you try to use the latest main branch 

> I have same issue no login on the web UI interface but in fact I can login PI os with ssh... But I am on buster
> 
> I can access, dev directly from http://ip-address/programming but not via login screen, the login as no effect/redirect
> 
> PRETTY_NAME="Raspbian GNU/Linux 10 (buster)" NAME="Raspbian GNU/Linux" VERSION_ID="10" VERSION="10 (buster)" VERSION_CODENAME=buster ID=raspbian ID_LIKE=debian HOME_URL="http://www.raspbian.org/" SUPPORT_URL="http://www.raspbian.org/RaspbianForums" BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Hi @gris74 , are you pulling from the latest dev branch? There is some updates commuted 2 days ago to the dev branch that may solve your issue. If the login problem still persists, please open the console of your browser and let me know if there is any error reporting in the login page. Thanks

**Comment by michaelhwn** [comment]
Hi @95ImadEL, the latest commit in the main branch now supports Bullseye, please feel free to try it out. But you will need to perform the setup process again on a newly flashed Raspberry Pi OS (Bullseye) due to a change in the software dependency.

**Comment by 95ImadEL** [comment]
@michaelhwn thank you so much I will check it 👍
