### ISSUE TITLE
Can't login in the Home Assistant Docker 

### ISSUE THREAD

**Issue by gris74** [cortictechnology/cep#17]
Hello, 

I find out that you install a docker with Hassio but I can't login.

I already have an Home Assistant server @home so I will unjoy your solution if I manage to integrate it.

**Comment by michaelhwn** [comment]
Hi @gris74, you can login the home assistant server with the following user:

username: ai
password: ai

**Comment by gris74** [comment]
Thx it work.... 

I am in a fresh installation and still encounter problems with libqtgui4 now and open an issue
