### ISSUE TITLE
Package libqtgui4 is not available

### ISSUE THREAD

**Issue by gris74** [cortictechnology/cep#18]
Package libqtgui4 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libqtgui4' has no installation candidate
E: Unable to locate package libqtwebkit4
E: Unable to locate package libqt4-test

For information :
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by michaelhwn** [comment]
Hi @gris74, did this happen while you are running the script? If so, did the setup script finish running and reboot the Pi?

**Comment by michaelhwn** [comment]
Hi @gris74, I have updated the main branch to remove the installation of libqtgui4 related packages during the setup process. Please give it a try.
