### ISSUE TITLE
Not able to access setup site 

### ISSUE THREAD

**Issue by philmurp** [cortictechnology/cep#21]
I am using VMWare Workstation since I dont have a Pi 4 and they are very hard to come by right now. I am running latest Pi OS; was able to download the CEP packages with success and Desktop rebooted.

I am able to SSH into the Pi so I believe that confirms we are on the same LAN and able to access the Pi. However, every time I run:

`http://<raspberry_pi_hostname>.local/setup`

I get an error "Connection was Reset". Tried on Chrome and Edge browsers. Any idea why I cant access the setup site, do I need to run any commands on the Pi desktop to trigger it to act like server?

Thanks!

**Comment by michaelhwn** [comment]
Hi @philmurp, I haven't tried to run on a VM yet. But you can try to access the setup page using the IP address directly: 

```http://<ip_of_vm>/setup```

If the VM is accessible within the local network, this approach should work.

**Comment by philmurp** [comment]
Not working with that, I am using same IP as I do with SSH (with success) and I get the "Site Cant Be Reached" "Connection was Reset"

**Comment by michaelhwn** [comment]
Hi @philmurp, can you use the following commands to check if the CAIT webapp and CURT backend is running properly in the VM? 

``` sudo journalctl -u cait_webapp.service```
```sudo journalctl -u curt_containers.service```

It is possible that these services are not running in the VM, and that could explain why you cannot access the web app.

**Comment by philmurp** [comment]
Thanks, looks like it isnt running as per image. Guess it didnt totally install correctly.

![Capture](https://user-images.githubusercontent.com/5831033/157300107-90f971df-bcfa-4d2d-acc4-34c3bfe99e57.PNG)

**Comment by michaelhwn** [comment]
Right, the services aren't starting. If you could copy and paste the error message here (the red lines), I may be able to help check what packages are missing in your image.

**Comment by philmurp** [comment]
Sorry got chopped off. New image attached:
![Uploading Capture_2.PNG…]()

**Comment by philmurp** [comment]
Repasted image:
![Capture_2](https://user-images.githubusercontent.com/5831033/157307753-47c59b5e-6681-44b8-84a9-b5c16eb29aa3.PNG)

**Comment by michaelhwn** [comment]
Ah, bash is missing. The CEP's installation script uses bash to execute commands, you can install bash before running the installation script: 

```sudo apt-get install bash -y```

**Comment by philmurp** [comment]
I double checked, and ran your install code; says bash is already the newest version (5.0-4). Rebooted and same error

**Comment by michaelhwn** [comment]
Can you type this and check where is bash located:

`which bash`

**Comment by michaelhwn** [comment]
I see, the problem is that the services use /usr/bin/bash to launch the startup scripts. In your image, bash is located at /bin/bash instead. This is a bit different from a standard Raspberry Pi OS installation. You will need to edit these files in order to run CEP in your image:

`sudo nano /etc/systemd/system/cait_webapp.service `
`sudo nano /etc/systemd/system/cait_webapp.service `

In both files, find the line starts with `ExecStart= ` and change `/usr/bin/bash` To `/bin/bash`. After that save and close the files. Restart the image and it should run.

**Comment by philmurp** [comment]
Thanks for all the help! Saw service started but some other issues;

First image for CAIT line
Second image for CURT line
![CAIT](https://user-images.githubusercontent.com/5831033/157320951-239c1d46-8faa-4dc1-90ec-629325917dcc.PNG)
![CURT](https://user-images.githubusercontent.com/5831033/157320973-70b2c8ec-adaf-432a-afe7-3325ca649fbd.PNG)

**Comment by michaelhwn** [comment]
This error is caused by a missing Python package, it should be installed through pip during the setup process. I think there were some errors during the installation process, it would be great if you can try to install again and capture the errors during the process.

**Comment by philmurp** [comment]
I try to re-run install script: First off I get this warning: 
![Capture](https://user-images.githubusercontent.com/5831033/158229897-855167da-fb68-4b84-ad4d-3c4c1d8a0cd5.PNG)

**Comment by philmurp** [comment]
I am running despite this warning; will update once it completes

**Comment by michaelhwn** [comment]
Sure, ignoring this warning is safe in this case as the docker command was initially installed through this script. [This line](https://github.com/cortictechnology/cep/blob/d3fb4bdbca744d4ae4e6a97c001a85506d67bd8b/setup.sh#L19) installs the Python packages that you were missing before, so if there are any errors happen, they should be related to pip. Please let me know if you observe any pip errors during the setup process.

**Comment by philmurp** [comment]
This time I am able to access initial setup screen, but not fully loading and some performance issues. I will try later today without anything else open. But at this point it may be my computer power/emulator issue

**Comment by michaelhwn** [comment]
Glad to know it's getting closer. For sure there can be some uncertainties when using an emulator to run the software. Please free feel to let me know if you need more help in debugging this approach.

**Comment by philmurp** [comment]
Will do, if I could just find a Raspberry Pi to buy I would have done that, but they have been out of stock for a while now. Any chance OrangePi, BananaPi type boards work with this software as alternate?

**Comment by michaelhwn** [comment]
Right, the chip shortage issue really affects a lot of things. I haven't tested with any of the Pi-alternative boards. However, from a technical perspective, since CEP is designed for running in a 32-bit Debian-based OS on a 64-bit Arm processor, with some efforts, it is very probable that it will run on those boards. But I cannot estimate the scope of work to do that, you will need to make sure the correct packages and dependencies of CEP are working well on those boards. If you want to go down this path, I am happy to offer some advice and help when you encounter issues.

**Comment by philmurp** [comment]
It seems to be working ok so far; but when using OAK D camera plugged in it says no OAK D device detected even though I can see it in my emulator window.

Do I need to download the DepthAI packages first? I thought they were included in this install but maybe not.

**Comment by michaelhwn** [comment]
No, you shouldn't need to manually install the DepthAI packages. All of the dependencies are installed into the corresponding Docker containers. Where did it say no OAK-D device is detected? Did it say that on the setup page, or on the programming page?

**Comment by michaelhwn** [comment]
I see all of the DepthAI related packages are installed in the vision Docker container, and that may not be running properly.  Within your VM, please run the following command and post the output messages here:

`sudo journalctl -u curt_containers.service -f`

**Comment by philmurp** [comment]
Attached here:
![1](https://user-images.githubusercontent.com/5831033/158271417-41fb9582-9326-488d-b4c4-7a59055562a7.PNG)

**Comment by michaelhwn** [comment]
Thanks for the log @philmurp. But it only shows the log of the homeassistant Docker container, did you see any logs that start with the name curt_vision?

**Comment by philmurp** [comment]
Nothing yet, I tried to leave the window open and re-run the cortic interface but still nothing starting with curt_vision. Maybe its not even starting?

Is it possible it has to do with my bash location? I did change the files like you mentioned above to get rid of /usr

**Comment by michaelhwn** [comment]
Right, I think the Docker containers are not running at all. We will need to see what happened when the containers were starting. To do that, you will need to open two terminals in the VM, in one of the terminals (let's call it the log terminal) enter `sudo journalctl -u curt_containers.service -f` and leave it printing the logs. In another terminal, you can enter `sudo systemctl restart curt_containers.service`. The log terminal should now show the Docker containers are being stopped and restarted. Please capture that log and post it here.

**Comment by philmurp** [comment]
![Capture2](https://user-images.githubusercontent.com/5831033/158277266-e89591e3-3369-45aa-a212-fb9989a0bc8a.PNG)
![Capture](https://user-images.githubusercontent.com/5831033/158277268-38ef4cb9-a1d8-4821-a186-09d9543149b2.PNG)

**Comment by michaelhwn** [comment]
The logs of the containers look ok so far, were there any messages that look like "Connected to broker..." and "Subscribing to topic..."? These messages indicate whether the MQTT broker was started successfully and if the different modules could connect to it.

**Comment by philmurp** [comment]
There is a "Fatal Python error: (pygame parachute) Segmentation Fault next to "curt_voice_1"

Also later on "error during setup
![Capture](https://user-images.githubusercontent.com/5831033/158281236-7328d2b3-09bd-43f9-a0e3-657d19a29b88.PNG)
 of component zeroconf" next to" homeassistant.setup"

**Comment by philmurp** [comment]
but then further down curt_vision_1 says "vision connected to broker with result code 0"

**Comment by michaelhwn** [comment]
I think there are multiple problems here:
1. The emulated audio hardware is not compatible with the CEP's voice module. This can only be solved by installing the proper driver within the voice container. This can be a tedious process as you need to figure out which driver to install, and you also need to maintain a local version of the voice container in your machine.
2. Although the OAK-D device is being detected, it cannot be properly used by the vision module within the VM. This may have something to do with the emulated USB hardware.

Both of these problems will need quiet a bit of effort to investigate. It may be better for you to wait until an actual Raspberry Pi 4B board is available, then run CEP on the actual hardware. If you really want to get it working in the VM, I suggest you to focus on getting the OAK-D device working first. It may have something to do with USB passthrough and permission settings related to the VM software you are using.

**Comment by philmurp** [comment]
Thanks for all the help, I will poke around VMWare settings a bit more.

I do have a Jetson Nano board; but it is 64 bit and runs on JetPack OS, so not sure how it will work. Might be worth a shot, not sure if you have heard anyone try this on that board.

**Comment by michaelhwn** [comment]
You are welcome @philmurp. If you want to try on the Jetson Nano. I recommend you to wait for a day or two as I am currently updating CEP to support the 64-bit Raspberry Pi OS.

**Comment by michaelhwn** [comment]
Hi @philmurp, I have tested that even the current version of CEP will work on 64bit Raspberry Pi OS. As long as the Docker containers can be run on the 64-bit OS you have, CEP should work. However, I suggest you to use the dev branch when you try setting it up. To check out the dev branch, please perform the following steps:

```
git clone https://github.com/cortictechnology/cep.git
cd cep
git checkout dev
```

**Comment by philmurp** [comment]
Thanks, ok just tried it on the Jetson Nano.

I got errors in the install, then once done I ran the code above to check if service was running (after updating the bash location) and got the extra two errors
![20220316_173513](https://user-images.githubusercontent.com/5831033/158706696-4b76a62f-d9d7-4376-a623-26477bf0d29b.jpg)
![20220316_191117](https://user-images.githubusercontent.com/5831033/158706707-0b7e824f-45f3-4d40-8041-5d2bf44db8a7.jpg)
.

**Comment by michaelhwn** [comment]
Hi @philmurp, the errors in the last picture are due to an incomplete setup process. You will need to fix the errors that happened in the setup and make sure the setup can finish properly. From the setup errors, I think you can look into 2 things:

1. NPM seems to be complaining about the platform being Linux-4.9.253-tegra, you should check if there are workarounds for NPM to accept this platform and continue with the package installation.
2. pip3 is not found, you may need to manually install pip3 into the OS before running the setup script.

**Comment by philmurp** [comment]
Thanks I was able to install NPM and pip3; still getting the attached error. It seems like online maybe the pip3 still isnt updated enough?

Still looking for some answers but thought I would post in case you recognize solution:
![Capture](https://user-images.githubusercontent.com/5831033/158871870-bc559810-6ab5-42af-96ea-42aea0fc0fcd.PNG)

**Comment by philmurp** [comment]
Made some updates to pip3 and seems like that error is gone, I am currently processing the setup, one error so far as below.

Do you think this is a showstopper that needs to be fixed?

![Capture](https://user-images.githubusercontent.com/5831033/158878123-21b44f10-dfce-4641-b612-b74b7dd39e30.PNG)

**Comment by michaelhwn** [comment]
Hi @philmurp, I found [this problem](https://stackoverflow.com/questions/69262518/problem-with-simpleeval-installationuse-2to3-invalid) in stackoverflow, maybe you can try the solution in it.

**Comment by philmurp** [comment]
Thanks I was able to install at version 57.5.0; currently downloading. 

Fingers crossed no errors yet, I will report back.

**Comment by philmurp** [comment]
So I was able to install with no errors; but when running the service, I still get below image. 
![Capture](https://user-images.githubusercontent.com/5831033/159037683-0ccf6516-df2b-4d65-8918-aa34d147057e.JPG)

**Comment by michaelhwn** [comment]
Hi @philmurp, this indicates that the environment variable in [this line](https://github.com/cortictechnology/cep/blob/d3fb4bdbca744d4ae4e6a97c001a85506d67bd8b/setup_scripts/start_cait.sh#L2) is not being set correctly during the setup process. The setup process set this variable for the root user in [this line](https://github.com/cortictechnology/cep/blob/d3fb4bdbca744d4ae4e6a97c001a85506d67bd8b/setup.sh#L52). You may want to make sure that this variable is set properly in `/root/.bashrc`.  If it is set, then you will need to make sure the `CAIT_WEB_PATH` variable is really pointing to the correct path (`<root_of_cep>/src/cait/cortic_webapp/`).

**Comment by philmurp** [comment]
Pic below:
1) Seems like this portion was added several times, should I make only one copy of each vairable (and one of the PYTHONPATHS is bigger than the others

2) should I remove /home/phil and just go straight to cep/src/cait/cortic_webapp/ because that is how I navigate from command line to get to this file

![Capture](https://user-images.githubusercontent.com/5831033/159053382-5cd24bf7-464e-46c8-80fe-90e93f50645b.JPG)

**Comment by philmurp** [comment]
I did those updates, same error. But when I navigate via command window I can find those files along the path specified.

![Capture](https://user-images.githubusercontent.com/5831033/159054079-e85c4d0e-6392-4fde-a0df-e0f8217bcfcf.JPG)

**Comment by michaelhwn** [comment]
It seems you have run the setup script multiple times. I would suggest starting the setup from scratch on a newly flashed OS again in the following order:
1. Flash a new OS installation.
2. Apply all of the fixes/tweaks you have done before to make sure the setup script run properly.
3. Clone the CEP project.
4. Run the setup.

If you just want a quick try, then yes, you should just keep one copy of each variable. 
And you should keep `/home/phil` as this is the part of the full path to the `<root_of_cep>`.

**Comment by philmurp** [comment]
Still having same issue; could it be this "E:" that comes up; it isnt in red color so I usually glanced over it.

Since its not Raspberry Pi I wouldnt expect my Jetson would have those headers; if you think that might be an issue I can see what options there are to install those specific headers.

![Capture](https://user-images.githubusercontent.com/5831033/159123997-745d7cf0-3c98-431f-a782-9d0af938a1a2.PNG)

**Comment by michaelhwn** [comment]
The error is due to [this line](https://github.com/cortictechnology/cep/blob/d3fb4bdbca744d4ae4e6a97c001a85506d67bd8b/setup.sh#L43). On a Raspberry Pi OS, this is needed to make sure the ReSpeaker driver can be properly installed in a later stage. If you don't have the intention to use the speech-related features of CEP. you can comment out this line in the setup script and perform the setup again.

**Comment by philmurp** [comment]
Still getting the missing file error; but the path is correct in bash file. Looking online I saw some posts about how permissions on the file location might be causing an issue.

I am still trying to figure out exactly what to fix on my example; but thought I would share if you think this might be a good path to follow for potential fix.

https://stackoverflow.com/questions/70668977/uwsgi-failed-to-open-python-file-root-wsgi-py-django

**Comment by philmurp** [comment]
File is present at the path specified; and my permissioning looks fine.

I am stumped on this one, some users online said could be python isnt in the same directory; not sure how that works I didnt do anything unqiue when downloading.

![Capture](https://user-images.githubusercontent.com/5831033/159362346-dfc01ef7-9511-485a-b1bb-59e49c394736.PNG)

**Comment by michaelhwn** [comment]
Hi @philmurp, the cait_webapp service uses root to run the webserver from the wsgi.py script, you would need to use `sudo python3 wsgi.py` to test if that is working.

**Comment by philmurp** [comment]
Not file found with that code:
![Capture](https://user-images.githubusercontent.com/5831033/159570837-25442d71-a5df-4542-ae6c-2dff055b37c4.PNG)

**Comment by michaelhwn** [comment]
Oh sorry @philmurp, I missed that you have used sudo in one of your screenshots. The error seems to be indicating that there are some API inconsistencies between the Python version in your system and the Python version CEP was written in. In Raspberry Pi OS (bullseye), the Python version is 3.9.2. While in your system, you are using Python 3.6. You may want to update the Python in your system to at least 3.9 and test again.

**Comment by philmurp** [comment]
I upgraded to 3.9.11. Also aliased both python and python3 = python3.9. Which worked based on picture below.

Same error:
![Uploading Capture.PNG…]()

**Comment by philmurp** [comment]
New error when I navigate to the file and then run it:
![Capture](https://user-images.githubusercontent.com/5831033/159575829-dd806917-381e-46a1-9f96-ad1ae9979e27.PNG)

**Comment by michaelhwn** [comment]
Hi @philmurp, can you confirm if the python3 version in root is also upgraded to 3.9? You can check by running 
```
sudo su
python3 --version
```

Regarding the new error, this is because the setup process was run with the previously installed Python 3.6 version, therefore, all of the necessary packages were installed for Python 3.6 only. You may need to do the setup again in the following order:
1. Flash a new OS installation.
2. Apply all of the fixes/tweaks you have done before to make sure the setup script run properly.
3. Upgrade Python version to 3.9.
4. Clone the CEP project.
5. Run the setup.

**Comment by philmurp** [comment]
Ah the sudo su, then python3 --version = 3.6.9. 

Any idea how to fix that?

**Comment by michaelhwn** [comment]
The quick way is to perform the alias operation you did before, but this time, do it under the root account:

```
sudo su
<perform python alias>
```

**Comment by philmurp** [comment]
Nice ok I got it to be 3.9.11 after I go to root. And now if I try to run wsgi.py manually, I get error no module names markupsafe.

So sounds like I need to perform a fresh re-install with python3.9 installed beforehand

**Comment by michaelhwn** [comment]
Yup, hope that solves your issues.

**Comment by michaelhwn** [comment]
Hi @philmurp, for the first screenshot, it seems the Python packages weren’t correctly installed for the Python 3.9 that you installed. For the second screenshot, you don’t need to run the setup using sudo. You can just run `bash  setup.sh`.

**Comment by philmurp** [comment]
Not sure what went wrong with the Python3.9 install; I still dont know why it cant find the wsgi.py under normal conditions but then I can navigate there and run it.

Are you saying python3.9 didnt install correctly because once I get to wsgi.py it shows "flask" missing?

**Comment by philmurp** [comment]
Given there are so many dependencies I might need to fix, I found this online Armbian.

Seems like its Debian style OS that can be used on ARM boards like Jetson Nano. Any thoughts on if its worth a shot?

docs.armbian.com/User-Guide_Getting-Started/

**Comment by michaelhwn** [comment]
I would say if the latest Armbian operating system is based on the latest Debian (Bullseye), there should be less dependency issues. And since it is a system closer than the latest Raspberry Pi OS, it may worth a try.

**Comment by philmurp** [comment]
Any chance me installing in the "git checkout dev" branch is causing issues?

**Comment by michaelhwn** [comment]
The dev branch's setup script is the same as the main branch. Since the problem happens during the setup process, it is not likely that was caused by the dev branch.

**Comment by philmurp** [comment]
Yeah not sure where its going wrong; the initial problem of python3: cant open file 'wsgi.py' : [Errno 2] No such file or directory is confusing me because the path is correct and I can clearly get to it.

Feel like I am somehow in a different directory or something.

**Comment by philmurp** [comment]
Some more interesting findings: I see in root root looks like maybe it is python2.7 still.

Perhaps I have to run code "sudo su" before all my installs/tweaks to ensure at root python is installed?
![Capture](https://user-images.githubusercontent.com/5831033/160010364-932f0ccb-3856-4a45-ad0d-d69d4ea65f9e.PNG)

**Comment by michaelhwn** [comment]
I think for Linux, the root/default Python version is closely related to the operating system. So there is a chance that the operating system you are using needs an upgrade in order to use Python 3.9 as the root/default Python.  Or you may even need to use other Linux distros that come with a newer Python version.

**Comment by michaelhwn** [comment]
The last screenshot you showed did suggest the root python3 still points to the 3.6 version though, which means the linking you did wasn't working for the root.

**Comment by philmurp** [comment]
But I am aliasing python3 -> python3.9; so it should be running python3.9 whenever called like that.

I think because my last screenshot I was opening the actual python3 folder so it shows python 3.6 but if the aliasing is working properly that version should never get used

**Comment by michaelhwn** [comment]
You can check which python3 is being used by running `which python3` In both the user account and root account (after `sudo su `). This way you can confirm if the alias is working.

**Comment by philmurp** [comment]
I found this page: https://www.itsupportwale.com/blog/how-to-upgrade-to-python-3-9-0-on-ubuntu-18-04-lts/ with some steps after install to update alternatives, maybe that will be better than alias.

![Capture](https://user-images.githubusercontent.com/5831033/160013960-de9fa4e8-4308-4af5-b903-7490bc716caf.PNG)

**Comment by michaelhwn** [comment]
Yes, it looks like the default python version is 3.9.11 now. If this method is used before the setup process, then all packaged installed during the setup process should be done with Python 3.9 then.

**Comment by philmurp** [comment]
Good news the install for sure used Pyhton3.9 because a lot more modules were being downloaded. 

Bad news, some more errors. I am looking through fixing them:

/usr/bin/aarch64-linux-gnu-gcc error came up about 4 times:
![Capture](https://user-images.githubusercontent.com/5831033/160111845-b0872f02-7b7a-4f05-b5ec-a64566c8cb78.PNG)

Could not find python2: Do I need to install Python2 as well?
![Capture](https://user-images.githubusercontent.com/5831033/160112170-28b0b0b8-92a9-48d7-b14c-8239d40f9c8e.PNG)


Not sure about this error; when building wheel for opencv-contrib-python:
![Capture](https://user-images.githubusercontent.com/5831033/160112423-32d6e8ca-a14d-4a0c-95eb-e809371dba6a.PNG)

**Comment by philmurp** [comment]
Fixed above, re-ran setup but still back to same error of cant find wsgi,py and when I manually navigate flask is missing.

Going to start from scratch again with the new python3.9-dev install before initial setup run to test again.

**Comment by michaelhwn** [comment]
Python2 should be installed already within the operating system you are using, so that's a weird error. But you are right to install the python3.9-dev package for the missing Python.h error. And the fact that there is only the Python error during the OpenCV installation/compilation process is a good sign, meaning all of the other OpenCV dependencies were installed.

**Comment by philmurp** [comment]
Still same cant direct to file error. I think it must be something due to my $PATH vs SUDO environment or something. Just cant figure this out

**Comment by michaelhwn** [comment]
Hi @philmurp, in the setup script, starting at [this line](https://github.com/cortictechnology/cep/blob/d3fb4bdbca744d4ae4e6a97c001a85506d67bd8b/setup.sh#L50), it adds the corresponding paths to the environmental variables to the root environment. The only reason I can think of for your issue is that these lines were being executed, or they were not suitable for your operating system. You can investigate a bit into this to make sure the path were added correctly during the setup process by these lines.

**Comment by philmurp** [comment]
Hello, I tried installing with Armbian image on the Jetson Nano; same error as before:

Note: I installed as root first since that was default, then once it reset it brought me to my user profile so after checking it didnt work I installed again not in root. That is second picture.

After installing only in root:
![wsgi issue](https://user-images.githubusercontent.com/5831033/162533971-667270c7-9c2c-4f9b-a51e-8d8da1c6395c.PNG)


After installing in user profile:
![wsgi issue2](https://user-images.githubusercontent.com/5831033/162534101-1869a0f5-539c-4760-bf1c-c896939dc18c.PNG)

**Comment by philmurp** [comment]
Hello, any alternative to Raspberry Pi 4? Still cant find any in stock.
