### ISSUE TITLE
Localhost is not working 

### ISSUE THREAD

**Issue by ArshadIram** [cortictechnology/cep#25]
Hello, 
We are using Raspberry Pi 4B and want to use the software "CAIT". 

We are following Readme file instructions and while completing the step we have faced an issue. The steps are below:
## Visual Programming 

1. Make sure your Raspberry Pi device is connected to the Local Area Network (LAN).
2. On a computer connected to the same LAN, go to ``http://<raspberry_pi_hostname>.local/setup`` on your browser and follow the instruction to complete the setup process. The Raspberry Pi device will reboot itself.
ONCE THIS STEP WAS COMPLETED OUR PI DEVICE RESTARTED AND THEN WE TRIED TO FOLLOW THIRD STEP BUT WE ARE NOW UNABLE TO ACCESS OUR LOCAL HOST. 

Can you please help us in resolving this issue?

Kind regards

**Comment by michaelhwn** [comment]
Hi @ArshadIram, may I know the following information:

1. Which operating systems you are running the browser to try accessing CAIT? 
2. What is the host name you use to access CAIT?
3. Could you please try to access CAIT through `http://<ip_address_of_cait>/setup` and see if that works?

**Comment by ArshadIram** [comment]
1.I am using ubuntu os on pi 4b 64gb device. I am using chromium browser. 
2. raspberrypi host name (IP), I am using to access CAIT
I am able to access now I think there might be server issue as same steps I was trying and now able to access. 

Many thanks for your quick reply.
