### ISSUE TITLE
Load Icon for loading examples

### ISSUE THREAD

**Issue by ArshadIram** [cortictechnology/cep#27]
Hi,

First of all thank you so much for the great work. We are trying to load the examples but unable to do so. These are the following steps we are following:
1. Click on Load button 
2. A window is open
3. We are getting error "Connect rest error and on networks files API is throwing error 

From the images you can see that the API is getting fail. 
![WhatsApp Image 2022-03-15 at 11 31 51 AM](https://user-images.githubusercontent.com/50909488/158369223-196c80ea-e38f-46de-ad67-a992b3b7bcb1.jpeg)
![WhatsApp Image 2022-03-15 at 11 31 51 AM (1)](https://user-images.githubusercontent.com/50909488/158369235-c0db7563-8fb6-48ce-b518-6081c59bde8f.jpeg)

**Comment by michaelhwn** [comment]
Hi @ArshadIram, it seems you are using the chromium browser, I will try to reproduce this issue on my end. Which operating system you are using with the chromium browser?

**Comment by ArshadIram** [comment]
I am using raspberry pi 4b and os is raspberrypi.

**Comment by ArshadIram** [comment]
Yes, It seems working to me now. I was getting error in morning. Many thanks to you.
