### ISSUE TITLE
Bash setup.sh setup is not working on OS 64-bit pi

### ISSUE THREAD

**Issue by ArshadIram** [cortictechnology/cep#30]
I git clone the folder 
cd cep and then git checkout dev 
after that I am trying to run this command bash setup.sh and the setup is stuck. Kindly, help me out in this setup
![20220402_225411](https://user-images.githubusercontent.com/50909488/161402697-a7c9177a-658f-4575-85ea-a19dcf36159b.png)

**Comment by kanhua** [comment]
What OS are you using 
My installation was also stuck at installing `opencv-contrib-python` when I tried to run the installation script on a 64-bit Raspberry Pi OS. But the installation went through when I used 32-bit Raspberry Pi OS.

Well, I also attempted to install the latest version of `opencv-contrib-python` but somehow it cannot launch `freetype`, which is essential to some code of this repository.

**Comment by ArshadIram** [comment]
I am using RaspberryPi os 64-bit 

My installation stuck OpenCV-contrib-python wheel

I tried to install this opencv seperatly but somehow I am not able to launch setup page.

**Comment by michaelhwn** [comment]
Hi @ArshadIram and @kanhua , it is known that the version of openCV used in this project needs to be compiled from scratch during installation on a 64 bit Raspberry Pi OS. The compilation time can last for hours on a Raspberry 4B. There is a pre-build package for the 32 bit OS and thus the installation time was fast. I will be trying to look for a version that can be used and has pre-build package on the 64 bit OS.
