### ISSUE TITLE
Install help please

### ISSUE THREAD

**Issue by DocObvious** [cortictechnology/cep#31]
Hello

I followed the instructions to install cep, from your github page, followed by the Respeak driver (although I am not using the mic). Everything seemed to install without issue the pi rebooted but when I try to go to http://raspberrypi.local/setup it says this site can’t be reached.

My setup is as follows:
Raspberry Pi 4 4gb model
64Gb sd card
fresh install 32 bit bullseye (this is the first thing I am doing on this fresh OS)
Offical raspberry pi dsi screen
Oak-d lite

As there are no error messages or faults I have nothing to use to troubleshoot the issue. 

Any help would be gratefully received.

Thanks, also posted on the cortic technologies web forum but no responses as yet so thought I would try here too.

**Comment by ArshadIram** [comment]
I am facing same issue

**Comment by kanhua** [comment]
I had the same issue earlier but I solved it.

What error message you got when you run 
```
>  sudo bash ./setup_scripts/start_cait.sh
```
In my case, it seemed that the latest version of `markupsafe` broke some backward compatibility. (Something like [this])(https://github.com/aws/aws-sam-cli/issues/3661)

```
sudo pip3 install markupsafe==2.0.1
```
worked for me.

**Comment by ArshadIram** [comment]
pi@raspberrypi:~ $ cd cep/
pi@raspberrypi:~/cep $  sudo bash ./setup_scripts/start_cait.sh
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/pi/cep/src/cait/cortic_webapp/wsgi.py", line 14, in <module>
    application.run(host="0.0.0.0", port=80, threaded=True)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 740, in init
    HTTPServer.init(self, server_address, handler)
  File "/usr/lib/python3.9/socketserver.py", line 452, in init
    self.server_bind()
  File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by DocObvious** [comment]
> I had the same issue earlier but I solved it.
> 
> What error message you got when you run
> 
> ```
> >  sudo bash ./setup_scripts/start_cait.sh
> ```
> 
> In my case, it seemed that the latest version of `markupsafe` broke some backward compatibility. (Something like [this])([aws/aws-sam-cli#3661](https://github.com/aws/aws-sam-cli/issues/3661))
> 
> ```
> sudo pip3 install markupsafe==2.0.1
> ```
> 
> worked for me.

This worked for me too thank you very much

**Comment by DocObvious** [comment]
> pi@raspberrypi:~ $ cd cep/ pi@raspberrypi:~/cep $ sudo bash ./setup_scripts/start_cait.sh
> 
> * Serving Flask app "main" (lazy loading)
> * Environment: production
>   WARNING: This is a development server. Do not use it in a production deployment.
>   Use a production WSGI server instead.
> * Debug mode: off
>   Traceback (most recent call last):
>   File "/home/pi/cep/src/cait/cortic_webapp/wsgi.py", line 14, in 
>   application.run(host="0.0.0.0", port=80, threaded=True)
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 990, in run
>   run_simple(host, port, self, **options)
>   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 1052, in run_simple
>   inner()
>   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 996, in inner
>   srv = make_server(
>   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 847, in make_server
>   return ThreadedWSGIServer(
>   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 740, in init
>   HTTPServer.init(self, server_address, handler)
>   File "/usr/lib/python3.9/socketserver.py", line 452, in init
>   self.server_bind()
>   File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
>   socketserver.TCPServer.server_bind(self)
>   File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
>   self.socket.bind(self.server_address)
>   OSError: [Errno 98] Address already in use

This error looks like the server is not running correctly. I don't know your setup but would consider doing a completely fresh install of raspberry pi os and trying to install CEP again on that.

**Comment by ArshadIram** [comment]
Do I need to checkout to dev branch during installation?  As per this bug fix https://github.com/cortictechnology/cep/issues/26. 

Kindly let me know

**Comment by DocObvious** [comment]
I am afraid that is beyond my knowledge base sorry. 

I can tell you I did a completely fresh raspberry pi os install of 32 bit bullseye the setup CEP as per the instructions and the applied the fix that was given in this tread and it worked.

**Comment by michaelhwn** [comment]
Hi @DocObvious, glad to know it works for you now.

**Comment by michaelhwn** [comment]
Hi @ArshadIram, from your log, it seems that port 80 is used by other programs running on the Raspberry Pi. CEP uses port 80 to host the frontend interface. If you have any other programs that is using port 80, CEP's frontend (CAIT) won't be able to run.
