### ISSUE TITLE
Can this be run on Debian and alternate board to Raspberry Pi?

### ISSUE THREAD

**Issue by philmurp** [cortictechnology/cep#34]
I am having trouble getting Raspberry Pi, they sell alternate boards that can run Debian do you think that will work for this software or it has to be Rasbian OS?

**Comment by michaelhwn** [comment]
Hi @philmurp, our software is targeted for the Raspberry Pi OS only, it is possible to modify it to support other Debian based OS. But we currently don’t have the capacity to work on this. You are welcome to contribute to the project and extend it to support other OS.
